name: Generate Spec ID
on:
  workflow_dispatch:
    inputs:
      request_id:
        description: 'Request ID for identifying this workflow run'
        required: false
        type: string
jobs:
  generate-spec-id:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Spec ID from run number
        id: generate
        run: |
          # GitHub Actionsが自動管理する実行回数を使用
          SPEC_ID=${{ github.run_number }}
          echo "spec_id=$SPEC_ID" >> $GITHUB_OUTPUT

          # Request IDがあれば出力
          if [ -n "${{ inputs.request_id }}" ]; then
            echo "Request ID: ${{ inputs.request_id }}"
          fi

      - name: Output result
        run: |
          echo "Spec ID: ${{ steps.generate.outputs.spec_id }}"